___

<a href='http://www.pieriandata.com'> <img src='../../Pierian_Data_Logo.png' /></a>
___

# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [1]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal.**

In [3]:
sal=pd.read_csv('Salaries.csv')

** Check the head of the DataFrame. **

In [4]:
sal.head(4)

   Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN

[4 rows x 13 columns]

** Use the .info() method to find out how many entries there are.**

In [5]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20086 entries, 0 to 20085
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                20086 non-null  int64
 1   EmployeeName      20086 non-null  object
 2   JobTitle          20086 non-null  object
 3   BasePay           20086 non-null  float64
 4   OvertimePay       20086 non-null  float64
 5   OtherPay          20086 non-null  float64
 6   Benefits          0 non-null      float64
 7   TotalPay          20086 non-null  float64
 8   TotalPayBenefits  20086 non-null  float64
 9   Year              20086 non-null  int64
 10  Notes             0 non-null      float64
 11  Agency            20085 non-null  object
 12  Status            0 non-null      float64
dtypes: float64(8), int64(2), object(3)
memory usage: 2.0+ MB

**What is the average BasePay ?**

In [6]:
sal[['BasePay']].mean()

BasePay    91984.201633
dtype: float64

** What is the highest amount of OvertimePay in the dataset ? **

In [7]:
sal['OvertimePay'].max()

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [ ]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [ ]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

** What is the name of highest paid person (including benefits)?**

In [ ]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]

   Id    EmployeeName  ...         Agency Status
0   1  NATHANIEL FORD  ...  San Francisco    NaN

[1 rows x 13 columns]

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [10]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]

          Id   EmployeeName  ... Agency  Status
20085  20086  ALMA SCHULMAN  ...    NaN     NaN

[1 rows x 13 columns]

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [12]:
sal.groupby('Year').mean()['BasePay']

Year
2011    91984.201633
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [ ]:
sal['JobTitle'].nunique()

2159

** What are the top 5 most common jobs? **

In [ ]:
sal['JobTitle'].value_counts().head(5)

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [ ]:
(sal[sal['Year']==2013]["JobTitle"].value_counts()==1).sum()

202

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [ ]:
c=0
for x in sal['JobTitle']:
  if 'Chief'in x:
    c+=1

In [ ]:
c

423

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

In [ ]:
sal['title_len']=sal['JobTitle'].str.len()

In [ ]:
sal[['title_len','TotalPayBenefits']].corr()

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!